[Icon Theme]
Name=Yume
Comment=Yume Icon & Cursors Theme
Inherits=breeze,elementary,gnome,hicolor

Example=folder

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

Directories=apps/scalable,apps/symbolic,devices/symbolic,emblems/scalable,emblems/symbolic,mimetypes/scalable,mimetypes/symbolic,panel,places/scalable,places/symbolic,status/scalable/16,status/scalable/32,status/scalable/512,status/symbolic


[apps/scalable]
Context=Applications
Size=512
MinSize=1
MaxSize=512
Type=Scalable

[apps/scalable]
Context=Applications
Size=16
Type=Fixed

[apps/scalable]
Context=Applications
Size=22
Type=Fixed

[apps/scalable]
Context=Applications
Size=24
Type=Fixed

[apps/symbolic]
Context=Applications
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[devices/symbolic]
Context=Devices
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[emblems/scalable]
Context=Emblems
Size=24
MinSize=1
MaxSize=512
Type=Scalable

[emblems/symbolic]
Context=Emblems
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[mimetypes/scalable]
Context=MimeTypes
Size=48
MinSize=1
MaxSize=512
Type=Scalable

[mimetypes/symbolic]
Context=MimeTypes
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[panel]
Context=Status
Size=24
MinSize=1
MaxSize=24
Type=Scalable

[places/scalable]
Context=Places
Size=512
MinSize=1
MaxSize=512
Type=Scalable

[places/symbolic]
Context=Places
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[status/scalable/16]
Context=Status
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[status/scalable/32]
Context=Status
Size=32
MinSize=1
MaxSize=512
Type=Scalable

[status/scalable/512]
Context=Status
Size=16
MinSize=1
MaxSize=512
Type=Scalable

[status/symbolic]
Context=Status
Size=16
MinSize=1
MaxSize=512
Type=Scalable
